console.log("Tsaryk");
let a = 35;
let b = "35Tsaryk";
console.log(a,b);
console.log(a + b);
b = a;
console.log(a,b);
console.log(a + b);
const str = "Hello my friend!";
var ff = 100;
let bb = true;
console.log(str);
console.log(ff);
console.log(!bb);
ff = null;
console.log(ff);
let uu;
console.log(uu);
let adult = confirm("Are you more 18 years?");
if(adult) alert("You are adult");
else alert("You aren't adult");
let n = "Vitaliy";
console.log(typeof n); 
let s = "Tsaryk";
console.log(typeof s); 
let i = 321;
console.log(typeof i);
let y = 2004;
console.log(typeof y);
let int = 123;
let bool = true;
var stri = "vvv";
let un, ss = null;
console.log(typeof int);
console.log(typeof bool);
console.log(typeof stri);
console.log(typeof un);
console.log(typeof ss);
var user = prompt("What is your name?", "Vitaliy");
var email = prompt("What is your email?", "viyaliktsaryk19@gmail.com");
var parol = prompt("What is your email?", "123456");
alert("Dear " + user + ", your email is " + email + ", your password is " + parol);
alert (" Seconds in Hours: " + 60 * 60 + "\nSeconds in Days: " + 60 * 60 * 24 + "\n Seconds in Month : " + 60 * 60 * 24 * 30);